name: CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
env:
  terraform-tflint-version: 'latest'
  
permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Install tflint
        run: |
          curl -L https://github.com/terraform-linters/tflint/releases/latest/download/tflint_linux_amd64.zip -o tflint.zip
          unzip tflint.zip
          sudo mv tflint /usr/local/bin/

      - name: Set up pre-commit
        run: pre-commit install --install-hooks

      - name: Format Terraform files
        run: terraform fmt -recursive

      - name: Checkov scan
        uses: bridgecrewio/checkov-action@master

      - name: Commit changes
        run: echo "No changes to commit"

  lint-test-deploy:
    name: Lint, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate
      
#       - name: Terraform Plan
#         id: plan
#         run: terraform plan -out=tfplan

#       # Additional steps for testing, deployment, etc.
      
#       - name: Terraform Apply
#         if: github.event_name == 'push'
#         run: terraform apply tfplan

#       - name: Terraform Destroy
#         run: terraform destroy -auto-approve
