name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Set up pre-commit
        run: |
          pre-commit install --install-hooks --no-verify

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

  lint-test-deploy:
    name: Lint, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt --check

      - name: Terraform Lint
        run: tflint

      - name: Terraform Validate
        run: terraform validate

      # Additional steps for testing, deployment, etc.

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
