name: Check Reusable Pipeline
on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  validate-and-run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate Reusable Pipeline
        run: |
          # Add commands or actions to validate the structure or behavior of the reusable pipeline
          # Example: Check if the reusable pipeline file exists
          if [[ ! -f ".github/workflows/action.yml" ]]; then
            echo "Reusable pipeline file '.github/workflows/blank.yml' does not exist."
            exit 1
          fi
          
          # Perform other validation or testing tasks as needed

      - name: Run Reusable Pipeline
        uses: ./.github/workflows/action.yml
        # Add inputs or configuration for the reusable pipeline as needed
