name: Check Reusable Pipeline

on:
  push:
    branches:
      - main
permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  validate-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Validate Reusable Pipeline
        run: |
          if [[ -z $(find . -name "blank.yml" -type f) ]]; then
            echo "Reusable pipeline file 'blank.yml' does not exist."
            exit 1
          fi
